### ISSUE TITLE
Warning when packaging `match's metavalue should be a valid match pattern string`

### ISSUE THREAD

**Issue by rxliuli** [FlandreDaisuki/rollup-plugin-userscript-metablock#14]
metablock.json

```json
{
  "match": [
    "https://app.slack.com/client/*",
    "http://127.0.0.1:*/*",
    "https://userjs.rxliuli.com/*"
  ]
}
```

![image](https://user-images.githubusercontent.com/24560368/95662114-3eea1f80-0b67-11eb-9685-98dc07053c01.png)

**Comment by FlandreDaisuki** [comment]
The match pattern is defined in [Chrome extension dev](https://developer.chrome.com/extensions/match_patterns) & [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns).

There is no description to `host:port` in Chrome, but MDN explicitly says it is an invalid match pattern:

>Note: The path pattern string should not include a port number. Adding a port, as in: "http://localhost:1234/*" causes the match pattern to be ignored. However, "http://localhost:1234" will match with "http://localhost/*"

To reduce the warning, I suggest you using `include` instead of `match` to `http://127.0.0.1:*/*` pattern.

**Comment by FlandreDaisuki** [comment]
If you have more questions, we can reopen it.
